# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-17 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersys', '0003_auto_20170917_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='confirmed_by_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
