# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-13 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersys', '0005_delete_proxyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
