# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-17 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordersys', '0006_auto_20171013_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарии к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='express_delivery',
            field=models.BooleanField(default=True, verbose_name='курьерская доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='имя, Фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ordersys.PickupPoint', verbose_name='пункты самовывоза'),
        ),
    ]
