# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-07 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersys', '0009_auto_20171102_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(max_length=4, verbose_name='количество'),
        ),
    ]
