# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-07 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersys', '0010_auto_20171107_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='количество'),
        ),
    ]
