# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-08 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordersys', '0011_auto_20171107_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='spec_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Spec_prod'),
        ),
    ]
