# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-03 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import ordersys.models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersys', '0012_auto_20171209_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[ordersys.models.validate_positive], verbose_name='количество'),
        ),
    ]
