# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Int_opt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Option_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Mark')),
                ('prod_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Prod_type')),
            ],
        ),
        migrations.CreateModel(
            name='Spec_prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('int_opts', models.ManyToManyField(to='catalog.Int_opt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('opt_list', models.ManyToManyField(to='catalog.Option_name')),
            ],
        ),
        migrations.CreateModel(
            name='Text_opt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Option_name')),
            ],
        ),
        migrations.AddField(
            model_name='spec_prod',
            name='text_opts',
            field=models.ManyToManyField(to='catalog.Text_opt'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Sub_type'),
        ),
        migrations.AddField(
            model_name='prod_type',
            name='sub_type_list',
            field=models.ManyToManyField(to='catalog.Sub_type'),
        ),
        migrations.AddField(
            model_name='int_opt',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Option_name'),
        ),
    ]
