# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_type',
            name='sub_type_list',
            field=models.ManyToManyField(blank=True, to='catalog.Sub_type'),
        ),
    ]
