# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170105_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='pictute',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
