# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170106_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Float_opt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Option_name')),
            ],
        ),
        migrations.AddField(
            model_name='spec_prod',
            name='float_opts',
            field=models.ManyToManyField(to='catalog.Float_opt'),
        ),
    ]
