# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170106_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec_prod',
            name='float_opts',
            field=models.ManyToManyField(blank=True, to='catalog.Float_opt'),
        ),
        migrations.AlterField(
            model_name='spec_prod',
            name='int_opts',
            field=models.ManyToManyField(blank=True, to='catalog.Int_opt'),
        ),
        migrations.AlterField(
            model_name='spec_prod',
            name='text_opts',
            field=models.ManyToManyField(blank=True, to='catalog.Text_opt'),
        ),
    ]
