# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20170107_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictute', models.ImageField(blank=True, upload_to='products/')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('text', models.CharField(blank=True, max_length=300)),
                ('link', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
