# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20170117_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='option_name',
            name='usage_in_filters',
            field=models.BooleanField(default=True),
        ),
    ]
