# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_option_name_usage_in_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod_type',
            name='sub_type_list',
        ),
        migrations.RemoveField(
            model_name='sub_type',
            name='opt_list',
        ),
        migrations.AlterModelOptions(
            name='option_name',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='prod_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_type',
        ),
        migrations.DeleteModel(
            name='Prod_type',
        ),
        migrations.DeleteModel(
            name='Sub_type',
        ),
    ]
