# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='float_opt',
            name='is_filter_for_category',
            field=models.ManyToManyField(blank=True, to='catalog.Category'),
        ),
        migrations.AddField(
            model_name='int_opt',
            name='is_filter_for_category',
            field=models.ManyToManyField(blank=True, to='catalog.Category'),
        ),
        migrations.AddField(
            model_name='text_opt',
            name='is_filter_for_category',
            field=models.ManyToManyField(blank=True, to='catalog.Category'),
        ),
    ]
