# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_option_name_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option_name',
            old_name='type',
            new_name='data_type',
        ),
    ]
