# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20170224_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_name',
            name='appearance_in_filters',
            field=models.CharField(blank=True, choices=[('1_col', 'значения в один столбец'), ('2_col', 'значения в два столбца'), ('interval', 'интервал от мин до макс')], max_length=70),
        ),
    ]
