# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_auto_20170226_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_name',
            name='data_type',
            field=models.CharField(choices=[('int', 'Целое число'), ('float', 'Десятичная дробь'), ('text', 'Текст')], max_length=20),
        ),
    ]
