# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20170226_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_name',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
