# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_auto_20170325_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale_card',
            name='link',
        ),
        migrations.AddField(
            model_name='sale_card',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale_card',
            name='params',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
